EXIT_SUCCESS = 0
EXIT_GENERAL_ERROR = 1
EXIT_CONFIG_ERROR = 2
EXIT_DUPLICATE_TARGET = 3
EXIT_CHECKSUM_MISMATCH = 4
EXIT_MISSING_FILE = 5
EXIT_DRILL_FAILED = 6
EXIT_REPORT_ERROR = 7
EXIT_HISTORY_ERROR = 8
EXIT_PROFILE_CONFLICT = 9
EXIT_PROFILE_INVALID_JSON = 10
EXIT_PROFILE_PERMISSION_DENIED = 11
EXIT_PROFILE_UNKNOWN_ALGORITHM = 12
EXIT_PROFILE_INVALID_CONFIG = 13

FILE_STATUS_MISSING = "missing"
FILE_STATUS_EXPIRED = "expired"
FILE_STATUS_CORRUPT = "corrupt"
FILE_STATUS_UNREGISTERED = "unregistered"
FILE_STATUS_OK = "ok"

CONFIG_FILENAME = "backup-manifest.yaml"
HISTORY_DIRNAME = ".backup-history"
PROFILE_LOG_DIRNAME = ".backup-profiles"
PROFILE_LOG_FILENAME = "profile-operations.log"
SUPPORTED_HASH_ALGORITHMS = {"md5", "sha1", "sha256", "sha512"}
